---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-mariadb
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.mariadb
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.mariadb
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_db
      dest:
        path: .values.endpoints.olso_db
    # Accounts
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.oslo_db.admin
      dest:
        path: .values.endpoints.oslo_db.auth.admin

    # Secrets
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_db_admin_password
        path: .

data:
  chart_name: ucp-mariadb
  release: ucp-mariadb
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      server:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
      prometheus_mysql_exporter:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    pod:
      replicas:
        server: 1
  dependencies:
    - mariadb-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: mariadb-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.mariadb-htk
      dest:
        path: .source
data:
  chart_name: mariadb-htk
  release: mariadb-htk
  namespace: mariadb-htk
  timeout: 100
  values: {}
  dependencies: []
...
