---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-services
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: UCP Services
  sequenced: true
  chart_group:
    - ucp-maas
    - ucp-tiller
    - ucp-armada
    - ucp-barbican
    - ucp-deckhand
    - ucp-promenade
    - ucp-shipyard
    - ucp-drydock
