---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-storage-provisioner
  labels:
    name: ucp-storage-provisioner
    group: ucp
    service: k8_storage_provisioning
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Kubernetes Storage Provisioner
  sequenced: true
  chart_group:
    - nfs_provisioner
