---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: coredns
  layeringDefinition:
    abstract: false
    layer: global
  labels:
    name: coredns
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.coredns
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.kubernetes.coredns
      dest:
        path: .values.images

    # Zones
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .dns.cluster_domain
      dest:
        path: .values.conf.coredns.corefile
        pattern: 'CLUSTER_DOMAIN'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.service_cidr
      dest:
        path: .values.conf.coredns.corefile
        pattern: 'SERVICE_CIDR'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.pod_cidr
      dest:
        path:  .values.conf.coredns.corefile
        pattern: 'POD_CIDR'

    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .dns.upstream_servers[0]
      dest:
        path: .values.conf.coredns.corefile
        pattern: 'UPSTREAM1'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .dns.upstream_servers[1]
      dest:
        path: .values.conf.coredns.corefile
        pattern: 'UPSTREAM2'
data:
  chart_name: coredns
  release: coredns
  namespace: kube-system
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values:
    conf:
      coredns:
        # TODO(alanmeadows) this needs to be adjusted to use substition
        corefile: |
          .:53 {
              errors
              health
              autopath @kubernetes
              kubernetes CLUSTER_DOMAIN SERVICE_CIDR POD_CIDR {
                pods insecure
                fallthrough in-addr.arpa ip6.arpa
                upstream UPSTREAM1
                upstream UPSTREAM2
              }
              prometheus :9153
              proxy . UPSTREAM1
              proxy . UPSTREAM2
              cache 30
          }
  dependencies:
    - coredns-htk
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: coredns-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.coredns-htk
      dest:
        path: .source
data:
  chart_name: coredns-htk
  release: coredns-htk
  namespace: coredns-htk
  timeout: 100
  values: {}
  dependencies: []
...
