---
schema: pegleg/SoftwareVersions/v1
metadata:
  schema: metadata/Document/v1
  name: software-versions
  labels:
    name: software-versions
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  charts:
    kubernetes:
      calico:
        etcd:
          type: git
          location: https://git.openstack.org/openstack/airship-promenade
          subpath: charts/etcd
          reference: 88c786b8e92d053fd0cba7237df68cc087b81f26
        etcd-htk:
          type: git
          location: https://git.openstack.org/openstack/openstack-helm-infra
          subpath: helm-toolkit
          reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
        calico:
          type: git
          location: https://git.openstack.org/openstack/openstack-helm-infra
          subpath: calico
          reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
        calico-htk:
          type: git
          location: https://git.openstack.org/openstack/openstack-helm-infra
          subpath: helm-toolkit
          reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      apiserver:
        type: git
        location: https://git.openstack.org/openstack/airship-promenade
        subpath: charts/apiserver
        reference: 88c786b8e92d053fd0cba7237df68cc087b81f26
      apiserver-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      controller-manager:
        type: git
        location: https://git.openstack.org/openstack/airship-promenade
        subpath: charts/controller_manager
        reference: 88c786b8e92d053fd0cba7237df68cc087b81f26
      controller-manager-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      coredns:
        type: git
        location: https://git.openstack.org/openstack/airship-promenade
        subpath: charts/coredns
        reference: 88c786b8e92d053fd0cba7237df68cc087b81f26
      coredns-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      haproxy:
        type: git
        location: https://git.openstack.org/openstack/airship-promenade
        subpath: charts/haproxy
        reference: 88c786b8e92d053fd0cba7237df68cc087b81f26
      haproxy-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      etcd:
        type: git
        location: https://git.openstack.org/openstack/airship-promenade
        subpath: charts/etcd
        reference: 88c786b8e92d053fd0cba7237df68cc087b81f26
      etcd-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      ingress:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: ingress
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      ingress-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      proxy:
        type: git
        location: https://git.openstack.org/openstack/airship-promenade
        subpath: charts/proxy
        reference: 88c786b8e92d053fd0cba7237df68cc087b81f26
      proxy-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      scheduler:
        type: git
        location: https://git.openstack.org/openstack/airship-promenade
        subpath: charts/scheduler
        reference: 88c786b8e92d053fd0cba7237df68cc087b81f26
      scheduler-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
    ucp:
      nfs_provisioner:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: nfs-provisioner
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      nfs_htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      armada:
        type: git
        location: https://git.openstack.org/openstack/airship-armada
        subpath: charts/armada
        reference: 9c3ebe68c76c62244d52a7f5ceffc2e955970290
      armada-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      barbican:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: barbican
        reference: 92b04a735d6a26e6cffc5c83a4a7dccfdebba2b7
      barbican-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      #TODO Update to split ceph charts
      ceph:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: ceph
        reference: f902cd14fac7de4c4c9f7d019191268a6b4e9601
      #TODO Update to new HTK with split ceph charts
      ceph-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: helm-toolkit
        reference: f902cd14fac7de4c4c9f7d019191268a6b4e9601
      deckhand:
        type: git
        location: https://git.openstack.org/openstack/airship-deckhand
        subpath: charts/deckhand
        reference: a0f00013b5db1def374fbd5b9f0009f704290bb1
      deckhand-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      divingbell:
        type: git
        location: https://git.openstack.org/openstack/airship-divingbell
        subpath: divingbell
        reference: 0ac90c40a0741a929204d139dfa0415562b7044e
      divingbell-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      drydock:
        type: git
        location: https://git.openstack.org/openstack/airship-drydock
        subpath: charts/drydock
        reference: f8c821e7219f84f12e3a90e3101c6f20d3049b5b
      # TODO waiting for https://review.openstack.org/#/c/595902/ to move to
      #      openstack-helm-infra version.
      drydock-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: helm-toolkit
        reference: f902cd14fac7de4c4c9f7d019191268a6b4e9601
      ingress:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: ingress
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      ingress-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      postgresql:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: postgresql
        reference: 92b04a735d6a26e6cffc5c83a4a7dccfdebba2b7
      postgresql-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      promenade:
        type: git
        location: https://git.openstack.org/openstack/airship-promenade
        subpath: charts/promenade
        reference: 88c786b8e92d053fd0cba7237df68cc087b81f26
      promenade-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      keystone:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: keystone
        reference: 92b04a735d6a26e6cffc5c83a4a7dccfdebba2b7
      keystone-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      maas:
        type: git
        location: https://git.openstack.org/openstack/airship-maas
        subpath: charts/maas
        # TODO(bryan-strassner) set to new version
        #     when https://review.openstack.org/#/c/595398/ is complete
        reference: refs/changes/98/595398/5
      maas-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      mariadb:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm
        subpath: mariadb
        reference: 92b04a735d6a26e6cffc5c83a4a7dccfdebba2b7
      mariadb-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      memcached:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: memcached
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      memcached-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      rabbitmq:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: rabbitmq
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      rabbitmq-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160
      shipyard:
        type: git
        location: https://git.openstack.org/openstack/airship-shipyard
        subpath: charts/shipyard
        reference: 0a14e7e80fb7b7bd41b29e9690f231229c1e95ca
      shipyard-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: bb3ff98d53c38a2ba70f506a8b6dc36207baa207
      tiller:
        type: git
        location: https://git.openstack.org/openstack/airship-armada
        subpath: charts/tiller
        reference: 9c3ebe68c76c62244d52a7f5ceffc2e955970290
      tiller-htk:
        type: git
        location: https://git.openstack.org/openstack/openstack-helm-infra
        subpath: helm-toolkit
        reference: b6fc24b9960bc6de29aa70c7d5b7725319046160

  files:
    kubelet: https://dl.k8s.io/v1.10.2/kubernetes-node-linux-amd64.tar.gz
  images:
    ucp:
      armada:
        api: quay.io/airshipit/armada:9c3ebe68c76c62244d52a7f5ceffc2e955970290
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
        ks_endpoints: docker.io/openstackhelm/heat:ocata
        ks_service: docker.io/openstackhelm/heat:ocata
        ks_user: docker.io/openstackhelm/heat:ocata
        helm: lachlanevenson/k8s-helm:v2.10.0
        tiller: gcr.io/kubernetes-helm/tiller:v2.10.0
      promenade:
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
        promenade: quay.io/airshipit/promenade:88c786b8e92d053fd0cba7237df68cc087b81f26
        ks_user: docker.io/openstackhelm/heat:ocata
        ks_service: docker.io/openstackhelm/heat:ocata
        ks_endpoints: docker.io/openstackhelm/heat:ocata
      deckhand:
        # pinned back to older version to prevent substitution errors with
        # newer version e.g.: fc03c6318a36fa60faf56ee79d91573fe7c60feb
        deckhand: quay.io/airshipit/deckhand:0ac33c233d59a731bf289db23ec4a882ff359168
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
        db_init: docker.io/postgres:9.5
        db_sync: quay.io/airshipit/deckhand:0ac33c233d59a731bf289db23ec4a882ff359168
        ks_endpoints: docker.io/openstackhelm/heat:ocata
        ks_service: docker.io/openstackhelm/heat:ocata
        ks_user: docker.io/openstackhelm/heat:ocata
      barbican:
        bootstrap: docker.io/openstackhelm/heat:ocata
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
        scripted_test: docker.io/openstackhelm/heat:ocata
        db_init: docker.io/openstackhelm/heat:ocata
        barbican_db_sync: docker.io/openstackhelm/barbican:ocata
        db_drop: docker.io/openstackhelm/heat:ocata
        ks_endpoints: docker.io/openstackhelm/heat:ocata
        ks_service: docker.io/openstackhelm/heat:ocata
        ks_user: docker.io/openstackhelm/heat:ocata
        barbican_api: docker.io/openstackhelm/barbican:ocata
      drydock:
        drydock: quay.io/airshipit/drydock:a41acdd7607ff5281d3df3ea435e15d5ff5c3f99
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
        ks_user: docker.io/openstackhelm/heat:ocata
        ks_service: docker.io/openstackhelm/heat:ocata
        ks_endpoints: docker.io/openstackhelm/heat:ocata
        drydock_db_init: docker.io/postgres:9.5
        drydock_db_sync: quay.io/airshipit/drydock:a41acdd7607ff5281d3df3ea435e15d5ff5c3f99
      shipyard:
        airflow: quay.io/airshipit/airflow:0a14e7e80fb7b7bd41b29e9690f231229c1e95ca
        shipyard: quay.io/airshipit/shipyard:0a14e7e80fb7b7bd41b29e9690f231229c1e95ca
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
        shipyard_db_init: docker.io/postgres:9.5
        shipyard_db_sync: quay.io/airshipit/shipyard:0a14e7e80fb7b7bd41b29e9690f231229c1e95ca
        airflow_db_init: docker.io/postgres:9.5
        airflow_db_sync: quay.io/airshipit/airflow:0a14e7e80fb7b7bd41b29e9690f231229c1e95ca
        ks_user: docker.io/openstackhelm/heat:ocata
        ks_service: docker.io/openstackhelm/heat:ocata
        ks_endpoints: docker.io/openstackhelm/heat:ocata
      maas:
        db_init: docker.io/postgres:9.5
        db_sync: quay.io/airshipit/maas-region-controller:dfb92ce07f87648f3423be11e51425923bc9f8b1
        maas_rack: quay.io/airshipit/maas-rack-controller:dfb92ce07f87648f3423be11e51425923bc9f8b1
        maas_region: quay.io/airshipit/maas-region-controller:dfb92ce07f87648f3423be11e51425923bc9f8b1
        bootstrap: quay.io/airshipit/maas-region-controller:dfb92ce07f87648f3423be11e51425923bc9f8b1
        export_api_key: quay.io/airshipit/maas-region-controller:dfb92ce07f87648f3423be11e51425923bc9f8b1
        # TODO: update to verified quay.io/airshipit/sstream-cache image
        maas_cache: quay.io/attcomdev/sstream-cache@sha256:sha256:90d0dc73785534ef6a3035265275e197a66727beeb9c979f60d3bbf31a6a8864
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
      keystone:
        keystone_bootstrap: docker.io/openstackhelm/heat:ocata
        test: docker.io/kolla/ubuntu-source-rally:4.0.0
        db_init: docker.io/openstackhelm/heat:ocata
        keystone_db_sync: docker.io/openstackhelm/keystone:ocata
        db_drop: docker.io/openstackhelm/heat:ocata
        keystone_fernet_setup: docker.io/openstackhelm/keystone:ocata
        keystone_fernet_rotate: docker.io/openstackhelm/keystone:ocata
        keystone_credential_setup: docker.io/openstackhelm/keystone:ocata
        keystone_credential_rotate: docker.io/openstackhelm/keystone:ocata
        keystone_api: docker.io/openstackhelm/keystone:ocata
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
      tiller:
        tiller: gcr.io/kubernetes-helm/tiller:v2.10.0
      mariadb:
        mariadb: docker.io/mariadb:10.1.23
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
      postgresql:
        postgresql: docker.io/postgres:9.5
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
      memcached:
        memcached: docker.io/memcached:1.5.5
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
      rabbitmq:
        rabbitmq: docker.io/rabbitmq:3.7
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
    #TODO Update to split ceph charts
    ceph:
      ceph:
        ks_endpoints: docker.io/openstackhelm/heat:ocata
        ks_service: docker.io/openstackhelm/heat:ocata
        ks_user: docker.io/openstackhelm/heat:ocata
        ceph_bootstrap: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
        ceph_daemon: docker.io/ceph/daemon:tag-build-master-luminous-ubuntu-16.04
        ceph_config_helper: docker.io/port/ceph-config-helper:v1.7.5
        ceph_rbd_provisioner: quay.io/external_storage/rbd-provisioner:v0.1.1
        ceph_cephfs_provisioner: quay.io/external_storage/cephfs-provisioner:v0.1.1
    storage:
      nfs_provisioner:
        nfs_provisioner: quay.io/kubernetes_incubator/nfs-provisioner:v1.0.8
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
        image_repo_sync: docker.io/docker:17.07.0
    kubernetes:
      apiserver:
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.10.2
        apiserver: gcr.io/google_containers/hyperkube-amd64:v1.10.2
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.0
      controller-manager:
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.10.2
        controller_manager: gcr.io/google_containers/hyperkube-amd64:v1.10.2
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.0
      coredns:
        coredns: coredns/coredns:1.0.5
      haproxy:
        haproxy: haproxy:1.8.3
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.10.2
      etcd:
        etcd: quay.io/coreos/etcd:v3.2.14
        etcdctl: quay.io/coreos/etcd:v3.2.14
      kubectl: gcr.io/google_containers/hyperkube-amd64:v1.10.2
      pause: gcr.io/google_containers/pause-amd64:3.0
      scheduler:
        anchor: gcr.io/google_containers/hyperkube-amd64:v1.10.2
        scheduler: gcr.io/google_containers/hyperkube-amd64:v1.10.2
      proxy:
        proxy: gcr.io/google_containers/hyperkube-amd64:v1.10.2
    calico:
      etcd:
        etcd: quay.io/coreos/etcd:v3.2.14
        etcdctl: quay.io/coreos/etcd:v3.2.14
      calico:
        cni: quay.io/calico/cni:v1.11.2
        ctl: quay.io/calico/ctl:v1.6.2
        kube_policy_controller: quay.io/calico/kube-policy-controller:v0.7.0
        node: quay.io/calico/node:v2.6.5
        settings: quay.io/calico/ctl:v1.6.2
  packages:
    named:
      docker: docker.io
      socat: socat=1.7.3.1-1
    unnamed:
      # nfs-common for the nfs provisioner - dev only.
      - nfs-common
      - ceph-common
