---
schema: shipyard/DeploymentConfiguration/v1
metadata:
  schema: metadata/Document/v1
  name: deployment-configuration
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
data:
  physical_provisioner:
    deployment_strategy: all-at-once
    deploy_interval: 30
    deploy_timeout: 3600
    destroy_interval: 30
    destroy_timeout: 900
    join_wait: 120
    prepare_node_interval: 30
    prepare_node_timeout: 1000
    prepare_site_interval: 10
    prepare_site_timeout: 300
    verify_interval: 10
    verify_timeout: 60
  kubernetes_provisioner:
    drain_timeout: 3600
    drain_grace_period: 1800
    clear_labels_timeout: 1800
    remove_etcd_timeout: 1800
    etcd_ready_timeout: 600
  armada:
    manifest: 'full-site'
