---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-keystone
  labels:
    component: keystone
    configuration: ldap-backed
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.keystone
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.keystone
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_db
      dest:
        path: .values.endpoints.oslo_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_cache
      dest:
        path: .values.endpoints.oslo_cache
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging.auth
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.oslo_db
      dest:
        path: .values.endpoints.oslo_db.auth.keystone
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.oslo_db.database
      dest:
        path: .values.endpoints.oslo_db.path
        pattern: DB_NAME

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.oslo_messaging.auth.keystone.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_messaging_password
        path: .
    - dest:
        path: .values.endpoints.oslo_messaging.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_messaging_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.keystone.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_oslo_db_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_db_admin_password
        path: .
data:
  chart_name: ucp-keystone
  release: ucp-keystone
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            job-name: keystone-db-sync
        - type: job
          labels:
            job-name: keystone-db-init
    post:
      create: []
  values:
    pods:
      replicas:
        api: 1
    labels:
      api:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled


  dependencies:
    - ucp-keystone-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name:  ucp-keystone-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.keystone-htk
      dest:
        path: .source
data:
  chart_name: ucp-keystone-htk
  release: ucp-keystone-htk
  namespace: ucp-keystone-htk
  timeout: 100
  values: {}
  dependencies: []
...
