---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-barbican
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.barbican
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.barbican
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.key_manager
      dest:
        path: .values.endpoints.key_manager
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_db
      dest:
        path: .values.endpoints.oslo_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_cache
      dest:
        path: .values.endpoints.oslo_cache
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging

    # Credentials
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.barbican.keystone
      dest:
        path: .values.endpoints.identity.auth.barbican
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.barbican.oslo_db
      dest:
        path: .values.endpoints.oslo_db.auth.barbican
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.barbican.oslo_db.database
      dest:
        path: .values.endpoints.oslo_db.path
        pattern: DB_NAME
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.barbican.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging.auth

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_db_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.barbican.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_barbican_keystone_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.barbican.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_barbican_oslo_db_password
        path: .
    - dest:
        path: .values.endpoints.oslo_messaging.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_messaging_password
        path: .
    - dest:
        path: .values.endpoints.oslo_messaging.auth.barbican.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_oslo_messaging_password
        path: .
data:
  chart_name: ucp-barbican
  release: ucp-barbican
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete: []
      create: []
    post:
      create: []
  values:
    labels:
      api:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
      test:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    pod:
      replicas:
        api: 1
  dependencies:
    - ucp-barbican-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-barbican-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.barbican-htk
      dest:
        path: .source
data:
  chart_name: ucp-barbican-htk
  release: ucp-barbican-htk
  namespace: ucp-barbican-htk
  timeout: 100
  values: {}
  dependencies: []
...
